"""Schemas package initialization."""
from app.schemas.user import (
    UserCreate,
    UserLogin,
    UserResponse,
    Token,
    ParentAccountCreate,
    ParentAccountResponse,
    ChildProfileCreate,
    ChildProfileUpdate,
    ChildProfileResponse,
)
from app.schemas.content import (
    MagazineCreate,
    MagazineResponse,
    ArticleCreate,
    ArticleResponse,
    QuizCreate,
    QuizResponse,
    QuizAnswer,
    QuizResult,
)
from app.schemas.puzzle import (
    PuzzleCreate,
    PuzzleResponse,
    PuzzleSubmission,
    PuzzleResult,
    UserPuzzleProgressResponse,
    PuzzleStats,
)
from app.schemas.gamification import (
    BadgeCreate,
    BadgeResponse,
    UserAchievementResponse,
    LeaderboardEntry,
    LeaderboardResponse,
    UserStats,
)

__all__ = [
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "Token",
    "ParentAccountCreate",
    "ParentAccountResponse",
    "ChildProfileCreate",
    "ChildProfileUpdate",
    "ChildProfileResponse",
    "MagazineCreate",
    "MagazineResponse",
    "ArticleCreate",
    "ArticleResponse",
    "QuizCreate",
    "QuizResponse",
    "QuizAnswer",
    "QuizResult",
    "PuzzleCreate",
    "PuzzleResponse",
    "PuzzleSubmission",
    "PuzzleResult",
    "UserPuzzleProgressResponse",
    "PuzzleStats",
    "BadgeCreate",
    "BadgeResponse",
    "UserAchievementResponse",
    "LeaderboardEntry",
    "LeaderboardResponse",
    "UserStats",
]
